package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javafx.scene.image.ImageView;

import javafx.scene.control.PasswordField;

public class LoginSceneController {
	@FXML
	private AnchorPane loginPane;
	@FXML
	private ImageView imgLogo;
	@FXML
	private TextField tfUser;
	@FXML
	private Button btnLogin;
	@FXML
	private Label lblNew;
	@FXML
	private Button btnSignup;
	@FXML
	private PasswordField tfPass;
	
	private DataCenter dc;
	private String currentUser;
	private Parent root;
	private Stage stage;
	private Scene scene;
	
	public void setInstance(DataCenter dc, String currentUser, Parent root, Stage stage, Scene scene) {
		this.dc = dc;
		this.currentUser = currentUser;
		this.root = root;
		this.stage = stage;
		this.scene = scene;
	}

	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void goToTimeline(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Alert alert = new Alert(AlertType.ERROR);
		if (tfPass.getText().isEmpty() || tfUser.getText().isEmpty() || dc.getUser(tfUser.getText().toLowerCase())==null) {
			alert.setContentText("Username or Password is Incorrect");
            alert.setHeaderText("Login Failed");
            alert.showAndWait();
		}
		else if (dc.getUser(tfUser.getText().toLowerCase()).getPassword().equals(tfPass.getText())) {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("HomeScene.fxml"));
			root = loader.load();
			scene = new Scene(root);
			currentUser = tfUser.getText().toLowerCase();
			HomeSceneController hsc = loader.getController();
			hsc.setInstance(dc, currentUser, root, stage, scene);
			stage.setScene(scene);
			stage.show();
		}
		else {
			alert.setContentText("Username or Password is Incorrect");
            alert.setHeaderText("Login Failed");
            alert.showAndWait();
		}
	}
	// Event Listener on Button[#btnSignup].onAction
	@FXML
	public void goToSignUp(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("SignupScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		SignupSceneController ssc = loader.getController();
		ssc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
}
