package application;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class OptionsSceneController {
	@FXML
	private TextField tfSearch;
	@FXML
	private ImageView imgLogo;
	@FXML
	private Button btnSearch;
	@FXML
	private ImageView btnProfile;
	@FXML
	private ImageView btnPost;
	@FXML
	private ImageView btnHome;
	@FXML
	private ImageView imgPfp;
	@FXML
	private TextField tfPfp;
	@FXML
	private Button btnChangePfp;
	@FXML
	private PasswordField tfOldPass;
	@FXML
	private PasswordField tfNewPass;
	@FXML
	private PasswordField tfConfirmPass;
	@FXML
	private Button btnChangePass;
	@FXML
	private ImageView btnLogout;
	
	private DataCenter dc;
	private String currentUser;
	private Parent root;
	private Stage stage;
	private Scene scene;
	
	public void setInstance(DataCenter dc, String currentUser, Parent root, Stage stage, Scene scene) {
		this.dc = dc;
		this.currentUser = currentUser;
		this.root = root;
		this.stage = stage;
		this.scene = scene;
		Image img = new Image(dc.getUser(currentUser).getPfp());
		btnProfile.setImage(img);
		imgPfp.setImage(img);
	}

	// Event Listener on Button[#btnSearch].onAction
	@FXML
	public void goToSearch(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("SearchScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		SearchSceneController ssc = loader.getController();
		ssc.setInstance(dc, currentUser, root, stage, scene, tfSearch.getText());
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnProfile].onMouseClicked
	@FXML
	public void goToProfile(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("ProfileScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		ProfileSceneController psc = loader.getController();
		psc.setInstance(dc, currentUser, root, stage, scene, currentUser);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnPost].onMouseClicked
	@FXML
	public void goToPost(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("PostScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		PostSceneController psc = loader.getController();
		psc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnHome].onMouseClicked
	@FXML
	public void goToHome(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("HomeScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		HomeSceneController hsc = loader.getController();
		hsc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button[#btnChangePfp].onAction
	@FXML
	public void changePfp(ActionEvent event) {
		// TODO Autogenerated
		Alert alert = new Alert(AlertType.INFORMATION);
		if (isValidImage(tfPfp.getText())) {
			dc.getUser(currentUser).setPfp(tfPfp.getText());
			Image img = new Image(tfPfp.getText());
			btnProfile.setImage(img);
			imgPfp.setImage(img);
			alert.setContentText("Profile Picture successfully changed.");
			alert.setHeaderText("Avatar Change Successful");
			alert.showAndWait();
			tfPfp.clear();
			dc.save();
		}
		else {
			alert.setAlertType(AlertType.WARNING);
			alert.setContentText("Profile Picture change was unsuccessful. Please enter a valid URL. (Supported filetypes .png, .jpeg, .gif)");
			alert.setHeaderText("Avatar Change Failed");
			alert.showAndWait();
		}
	}
	// Event Listener on Button[#btnChangePass].onAction
	@FXML
	public void changePassword(ActionEvent event) {
		// TODO Autogenerated
		Alert alert = new Alert(AlertType.WARNING);
		if (!dc.getUser(currentUser).getPassword().equals(tfOldPass.getText()) || !tfNewPass.getText().equals(tfConfirmPass.getText()) || tfNewPass.getText().isEmpty()) {
			alert.setContentText("Password change was unsuccessful. Make sure all fields are filled out and spelled correctly.");
			alert.setHeaderText("Password Change Unsuccessful");
			alert.showAndWait();
		}
		else {
			dc.getUser(currentUser).setPassword(tfNewPass.getText());
			alert.setAlertType(AlertType.INFORMATION);
			alert.setContentText("Password change was successful.");
			alert.setHeaderText("Password Change Successful");
			alert.showAndWait();
			dc.save();
			tfNewPass.clear();
			tfOldPass.clear();
			tfConfirmPass.clear();
		}
	}
	// Event Listener on ImageView[#btnLogout].onMouseClicked
	@FXML
	public void goToLogin(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("LoginScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		currentUser = "";
		LoginSceneController lsc = loader.getController();
		lsc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	
	public boolean isValidImage(String url) {
		try {  
			Image image = new Image(url);
			if (image.getHeight()==0) {
				return false;
			}
			else {
				return true;
			}
	    }
		catch (IllegalArgumentException e) {
			return false;
		}
		
	}
}
