package application;

import java.io.IOException;
import java.util.Iterator;
import java.util.LinkedList;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Insets;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.stage.Stage;

public class ProfileSceneController {
	@FXML
	private TextField tfSearch;
	@FXML
	private ImageView imgLogo;
	@FXML
	private Button btnSearch;
	@FXML
	private ImageView btnProfile;
	@FXML
	private ImageView btnPost;
	@FXML
	private ImageView btnHome;
	@FXML
	private ImageView btnOptions;
	@FXML
	private Label lblUsername;
	@FXML
	private ImageView imgUserPfp;
	@FXML
	private ScrollPane spUserPosts;
	@FXML
	private VBox vboxPosts;
	@FXML
	private Button btnFollow;
	@FXML
	private ImageView btnLogout;

	private DataCenter dc;
	private String currentUser;
	private Parent root;
	private Stage stage;
	private Scene scene;
	private String profileUser;
	
	public void setInstance(DataCenter dc, String currentUser, Parent root, Stage stage, Scene scene, String profileUser) {
		this.dc = dc;
		this.currentUser = currentUser;
		this.root = root;
		this.stage = stage;
		this.scene = scene;
		this.profileUser = profileUser;
		lblUsername.setText(dc.getUser(profileUser).getUsername());
		btnProfile.setImage(new Image(dc.getUser(currentUser).getPfp()));
		imgUserPfp.setImage(new Image(dc.getUser(profileUser).getPfp()));
		if (currentUser.equals(profileUser)) {
			btnFollow.setDisable(true);
		}
		if (dc.getUser(currentUser).isFollowing(profileUser)) {
			btnFollow.setText("Unfollow");
		}
		
		setUserPosts();
	}
	
	public void setUserPosts() {
		LinkedList<Integer> posts = new LinkedList<Integer>();
		for (int i=dc.getPostBagSize()-1;i>=0;--i) {
			if (dc.getPost(i).getUser().equals(profileUser) && !dc.getPost(i).isReply()) {
				posts.add(dc.getPost(i).getKey());
			}
		}
		
		Iterator<Integer> iterator = posts.iterator();
		while (iterator.hasNext()) {
			Post tmpPost = dc.getPost(iterator.next());
			User tmpUser = dc.getUser(dc.getPost(tmpPost.getKey()).getUser());
			HBox hboxPost = new HBox();
			ImageView imgPfp = new ImageView();
			imgPfp.setImage(new Image(tmpUser.getPfp()));
			imgPfp.setFitHeight(100);
			imgPfp.setFitWidth(100);
			Label lblPostInfo = new Label(dc.getUser(tmpPost.getUser()).getUsername() + " " + tmpPost.getTime() + ": " + tmpPost.getText() + "\nLikes: " + tmpPost.likesSize());
			lblPostInfo.setFont(new Font(20));
			lblPostInfo.setWrapText(true);
			hboxPost.getChildren().addAll(imgPfp, lblPostInfo);
			hboxPost.setSpacing(5);
			vboxPosts.getChildren().add(hboxPost);
			vboxPosts.setSpacing(10);
			vboxPosts.setPadding(new Insets(5));
			
			hboxPost.setOnMouseClicked(e->{
				FXMLLoader loader = new FXMLLoader(getClass().getResource("ThreadScene.fxml"));
				try {
					root = loader.load();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				scene = new Scene(root);
				ThreadSceneController tsc = loader.getController();
				tsc.setInstance(dc, currentUser, root, stage, scene, tmpPost);
				stage.setScene(scene);
				stage.show();
			});
		}
	}

	// Event Listener on Button[#btnSearch].onAction
	@FXML
	public void goToSearch(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("SearchScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		SearchSceneController ssc = loader.getController();
		ssc.setInstance(dc, currentUser, root, stage, scene, tfSearch.getText());
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnProfile].onMouseClicked
	@FXML
	public void goToProfile(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("ProfileScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		ProfileSceneController psc = loader.getController();
		psc.setInstance(dc, currentUser, root, stage, scene, currentUser);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnPost].onMouseClicked
	@FXML
	public void goToPostmaker(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("PostScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		PostSceneController psc = loader.getController();
		psc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnHome].onMouseClicked
	@FXML
	public void goToHome(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("HomeScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		HomeSceneController hsc = loader.getController();
		hsc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnOptions].onMouseClicked
	@FXML
	public void goToOptions(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("OptionsScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		OptionsSceneController osc = loader.getController();
		osc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button[#btnFollow].onAction
	@FXML
	public void followUser(ActionEvent event) {
		// TODO Autogenerated
		if (dc.getUser(currentUser).isFollowing(profileUser)) {
			dc.getUser(currentUser).unfollow(profileUser);
			dc.getUser(profileUser).removeFollower(currentUser);
			btnFollow.setText("Follow");
			dc.save();
		}
		else {
			dc.getUser(currentUser).addFollowing(profileUser);
			dc.getUser(profileUser).addFollower(currentUser);
			btnFollow.setText("Unfollow");
			dc.save();
		}
	}
	// Event Listener on ImageView[#btnLogout].onMouseClicked
	@FXML
	public void goToLogin(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("LoginScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		currentUser = "";
		LoginSceneController lsc = loader.getController();
		lsc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
}
