package application;

import java.io.IOException;
import java.util.Iterator;
import java.util.LinkedList;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Insets;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.KeyEvent;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.HBox;
import javafx.scene.text.Font;
import javafx.stage.Stage;

public class ReplySceneController {
	@FXML
	private TextField tfSearch;
	@FXML
	private ImageView imgLogo;
	@FXML
	private Button btnSearch;
	@FXML
	private ImageView btnProfile;
	@FXML
	private ImageView btnPost;
	@FXML
	private ImageView btnHome;
	@FXML
	private ImageView btnOptions;
	@FXML
	private TextArea taPost;
	@FXML
	private ImageView imgPfp;
	@FXML
	private Label lblUsername;
	@FXML
	private Button btnReply;
	@FXML
	private ScrollPane spOP;
	@FXML
	private HBox hboxOP;
	@FXML
	private ImageView btnLogout;
	@FXML
	private TextArea taSpellCheck;
	@FXML
	private ImageView btnBack;
	
	private DataCenter dc;
	private String currentUser;
	private Parent root;
	private Stage stage;
	private Scene scene;
	private Post originalPost;
	
	public void setInstance(DataCenter dc, String currentUser, Parent root, Stage stage, Scene scene, Post originalPost) {
		this.dc = dc;
		this.currentUser = currentUser;
		this.root = root;
		this.stage = stage;
		this.scene = scene;
		this.originalPost = originalPost;
		lblUsername.setText(currentUser);
		Image img = new Image(dc.getUser(currentUser).getPfp());
		btnProfile.setImage(img);
		imgPfp.setImage(img);
		
		HBox hboxOP = new HBox();
		ImageView imgOPPfp = new ImageView();
		imgOPPfp.setImage(new Image(dc.getUser(originalPost.getUser()).getPfp()));
		imgOPPfp.setFitHeight(100);
		imgOPPfp.setFitWidth(100);
		Label lblOPostInfo = new Label(dc.getUser(originalPost.getUser()).getUsername() + " " + originalPost.getTime() + ": " + originalPost.getText()  + "\nLikes: " + originalPost.likesSize());
		lblOPostInfo.setFont(new Font(20));
		lblOPostInfo.setWrapText(true);
		hboxOP.getChildren().addAll(imgOPPfp, lblOPostInfo);
		hboxOP.setSpacing(5);
		hboxOP.setPadding(new Insets(5));
		spOP.setContent(hboxOP);
	}

	// Event Listener on Button[#btnSearch].onAction
	@FXML
	public void goToSearch(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("SearchScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		SearchSceneController ssc = loader.getController();
		ssc.setInstance(dc, currentUser, root, stage, scene, tfSearch.getText());
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnProfile].onMouseClicked
	@FXML
	public void goToProfile(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("ProfileScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		ProfileSceneController psc = loader.getController();
		psc.setInstance(dc, currentUser, root, stage, scene, currentUser);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnPost].onMouseClicked
	@FXML
	public void goToPostmaker(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("PostScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		PostSceneController psc = loader.getController();
		psc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnHome].onMouseClicked
	@FXML
	public void goToHome(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("HomeScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		HomeSceneController hsc = loader.getController();
		hsc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnOptions].onMouseClicked
	@FXML
	public void goToOptions(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("OptionsScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		OptionsSceneController osc = loader.getController();
		osc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on TextArea[#taPost].onKeyTyped
	@FXML
	public void spellCheck(KeyEvent event) {
		// TODO Autogenerated
		taSpellCheck.setText("");
		String[] words = taPost.getText().split("\s+");
		LinkedList<String> misspelledWords = new LinkedList<String>();
        for (String word : words) {
        	if (!dc.containsWord(word)) {
        		misspelledWords.add(word);
            }
        }
        Iterator<String> iterator = misspelledWords.iterator();
        while (iterator.hasNext()) {
        	taSpellCheck.setText(taSpellCheck.getText() + iterator.next() + "\n");
        }
	}
	// Event Listener on Button[#btnReply].onAction
	@FXML
	public void doReply(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Alert alert = new Alert(AlertType.INFORMATION);
		if (taPost.getText().isEmpty()) {
			alert.setAlertType(AlertType.ERROR);
			alert.setContentText("Reply cannot be blank");
			alert.setHeaderText("Reply Creation Unsuccessful");
			alert.showAndWait();
		}
		else {
			Post post = new Post(taPost.getText(), currentUser, dc.getPostBagSize(), true);
			dc.addPost(post);
			dc.getPost(originalPost.getKey()).addReply(post.getKey());
			alert.setContentText("Reply was made successfully!");
			alert.setHeaderText("Reply Creation Successful");
			alert.showAndWait();
			
			dc.save();
			
			FXMLLoader loader = new FXMLLoader(getClass().getResource("ThreadScene.fxml"));
			root = loader.load();
			scene = new Scene(root);
			ThreadSceneController tsc = loader.getController();
			tsc.setInstance(dc, currentUser, root, stage, scene, originalPost);
			stage.setScene(scene);
			stage.show();
		}
	}
	// Event Listener on ImageView[#btnLogout].onMouseClicked
	@FXML
	public void goToLogin(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("LoginScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		currentUser = "";
		LoginSceneController lsc = loader.getController();
		lsc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnBack].onMouseClicked
	@FXML
	public void goToThread(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("ThreadScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		ThreadSceneController tsc = loader.getController();
		tsc.setInstance(dc, currentUser, root, stage, scene, originalPost);
		stage.setScene(scene);
		stage.show();
	}
}
