package application;

import java.io.IOException;
import java.util.ArrayList;

import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class SearchSceneController {
	@FXML
	private TextField tfSearch;
	@FXML
	private ImageView imgLogo;
	@FXML
	private Button btnSearch;
	@FXML
	private ImageView btnProfile;
	@FXML
	private ImageView btnPost;
	@FXML
	private ImageView btnHome;
	@FXML
	private ImageView btnOptions;
	@FXML
	private ListView<String> lvResults;
	@FXML
	private ImageView btnLogout;

	
	private DataCenter dc;
	private String currentUser;
	private Parent root;
	private Stage stage;
	private Scene scene;
	
	public void setInstance(DataCenter dc, String currentUser, Parent root, Stage stage, Scene scene, String query) {
		this.dc = dc;
		this.currentUser = currentUser;
		this.root = root;
		this.stage = stage;
		this.scene = scene;
		btnProfile.setImage(new Image(dc.getUser(currentUser).getPfp()));
		
		ArrayList<String> users = new ArrayList<>(dc.getListofUsers());
		if (query.isEmpty()) {
			for (int i=0;i<users.size();++i) {
				lvResults.getItems().add(users.get(i));
			}
		}
		else {
			for (int i=0;i<users.size();++i) {
				if (users.get(i).toLowerCase().contains(query.toLowerCase())) {
					lvResults.getItems().add(users.get(i));
				}
			}
		}
		
		lvResults.getSelectionModel().selectedItemProperty().addListener(new ChangeListener<String>() {
			public void changed(ObservableValue<? extends String> arg0, String arg1, String arg2) {
				FXMLLoader loader = new FXMLLoader(getClass().getResource("ProfileScene.fxml"));
				Parent root = null;
				try {
					root = loader.load();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				Scene scene = new Scene(root);
				ProfileSceneController psc = loader.getController();
				psc.setInstance(dc, currentUser, root, stage, scene, lvResults.getSelectionModel().getSelectedItem());
				stage.setScene(scene);
				stage.show();
			}
		});
	}

	// Event Listener on Button[#btnSearch].onAction
	@FXML
	public void goToSearch(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("SearchScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		SearchSceneController ssc = loader.getController();
		ssc.setInstance(dc, currentUser, root, stage, scene, tfSearch.getText());
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnProfile].onMouseClicked
	@FXML
	public void goToProfile(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("ProfileScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		ProfileSceneController psc = loader.getController();
		psc.setInstance(dc, currentUser, root, stage, scene, currentUser);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnPost].onMouseClicked
	@FXML
	public void goToPostmaker(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("PostScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		PostSceneController psc = loader.getController();
		psc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnHome].onMouseClicked
	@FXML
	public void goToHome(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("HomeScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		HomeSceneController hsc = loader.getController();
		hsc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnOptions].onMouseClicked
	@FXML
	public void goToOptions(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("OptionsScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		OptionsSceneController osc = loader.getController();
		osc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnLogout].onMouseClicked
	@FXML
	public void goToLogin(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("LoginScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		currentUser = "";
		LoginSceneController lsc = loader.getController();
		lsc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
}
