package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.image.ImageView;
import javafx.stage.Stage;
import javafx.scene.control.PasswordField;

public class SignupSceneController {
	@FXML
	private ImageView imgLogo;
	@FXML
	private TextField tfUser;
	@FXML
	private Button btnSignup;
	@FXML
	private PasswordField tfPass;
	@FXML
	private Button btnLogin;

	private DataCenter dc;
	private String currentUser;
	private Parent root;
	private Stage stage;
	private Scene scene;
	
	public void setInstance(DataCenter dc, String currentUser, Parent root, Stage stage, Scene scene) {
		this.dc = dc;
		this.currentUser = currentUser;
		this.root = root;
		this.stage = stage;
		this.scene = scene;
	}
	// Event Listener on Button[#btnSignup].onAction
	@FXML
	public void goToLogin(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Alert alert = new Alert(AlertType.ERROR);
		if (tfUser.getText().isEmpty() || tfPass.getText().isEmpty()) {
			alert.setContentText("Username or Password cannot be Blank.");
            alert.setHeaderText("Signup Failed");
            alert.showAndWait();
		}
		else if (dc.getUser(tfUser.getText().toLowerCase())!=null) {
			alert.setContentText("Username is taken.");
            alert.setHeaderText("Signup Failed");
            alert.showAndWait();
		}
		else {
			dc.addUser(new User(tfUser.getText().toLowerCase(), tfPass.getText()));
			alert.setAlertType(AlertType.INFORMATION);
			alert.setContentText("Profile successfully created.");
			alert.setHeaderText("Signup Successful");
			alert.showAndWait();
			FXMLLoader loader = new FXMLLoader(getClass().getResource("LoginScene.fxml"));
			root = loader.load();
			scene = new Scene(root);
			LoginSceneController ssc = loader.getController();
			ssc.setInstance(dc, currentUser, root, stage, scene);
			stage.setScene(scene);
			stage.show();
		}
	}
	
	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void goBackToLogin(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("LoginScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		LoginSceneController lsc = loader.getController();
		lsc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
}
