package application;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Insets;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.stage.Stage;

public class ThreadSceneController {
	@FXML
	private TextField tfSearch;
	@FXML
	private ImageView imgLogo;
	@FXML
	private Button btnSearch;
	@FXML
	private ImageView btnProfile;
	@FXML
	private ImageView btnPost;
	@FXML
	private ImageView btnHome;
	@FXML
	private ImageView btnOptions;
	@FXML
	private ScrollPane spThread;
	@FXML
	private VBox vboxThread;
	@FXML
	private ImageView btnLike;
	@FXML
	private ImageView btnReply;
	@FXML
	private ImageView btnLogout;
	private Label lblOPostInfo;
	
	private DataCenter dc;
	private String currentUser;
	private Parent root;
	private Stage stage;
	private Scene scene;
	private Post originalPost;
	
	public void setInstance(DataCenter dc, String currentUser, Parent root, Stage stage, Scene scene, Post originalPost) {
		this.dc = dc;
		this.currentUser = currentUser;
		this.root = root;
		this.stage = stage;
		this.scene = scene;
		this.originalPost = originalPost;
		btnProfile.setImage(new Image(dc.getUser(currentUser).getPfp()));
		if (originalPost.isLiked(currentUser)) {
			btnLike.setImage(new Image("liked.png"));
		}
		else {
			btnLike.setImage(new Image("unliked.png"));
		}
		setThread();
	}
	
	public void setThread() {
		HBox hboxOP = new HBox();
		ImageView imgOPPfp = new ImageView();
		imgOPPfp.setImage(new Image(dc.getUser(originalPost.getUser()).getPfp()));
		imgOPPfp.setFitHeight(100);
		imgOPPfp.setFitWidth(100);
		lblOPostInfo = new Label(dc.getUser(originalPost.getUser()).getUsername() + " " + originalPost.getTime() + ": " + originalPost.getText()  + "\nLikes: " + originalPost.likesSize());
		lblOPostInfo.setFont(new Font(20));
		lblOPostInfo.setWrapText(true);
		hboxOP.getChildren().addAll(imgOPPfp, lblOPostInfo);
		hboxOP.setSpacing(5);
		vboxThread.getChildren().add(hboxOP);
		vboxThread.setSpacing(10);
		vboxThread.setPadding(new Insets(5));
		
		
		for (int i=0;i<originalPost.getRepliesSize();++i) {
			Post tmpReply = dc.getPost(originalPost.getReply(i));
			User tmpUser = dc.getUser(tmpReply.getUser());
			HBox hboxPost = new HBox();
			ImageView imgPfp = new ImageView();
			imgPfp.setImage(new Image(tmpUser.getPfp()));
			imgPfp.setFitHeight(100);
			imgPfp.setFitWidth(100);
			Label lblPostInfo = new Label(dc.getUser(tmpReply.getUser()).getUsername() + " " + tmpReply.getTime() + ": " + tmpReply.getText() + "\nLikes: " + tmpReply.likesSize());
			lblPostInfo.setFont(new Font(20));
			lblPostInfo.setWrapText(true);
			hboxPost.getChildren().addAll(imgPfp, lblPostInfo);
			hboxPost.setSpacing(5);
			vboxThread.getChildren().add(hboxPost);
			
			hboxPost.setOnMouseClicked(e->{
				FXMLLoader loader = new FXMLLoader(getClass().getResource("ThreadScene.fxml"));
				try {
					root = loader.load();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				scene = new Scene(root);
				ThreadSceneController tsc = loader.getController();
				tsc.setInstance(dc, currentUser, root, stage, scene, tmpReply);
				stage.setScene(scene);
				stage.show();
			});
		}
	}

	// Event Listener on Button[#btnSearch].onAction
	@FXML
	public void goToSearch(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("SearchScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		SearchSceneController ssc = loader.getController();
		ssc.setInstance(dc, currentUser, root, stage, scene, tfSearch.getText());
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnProfile].onMouseClicked
	@FXML
	public void goToProfile(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("ProfileScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		ProfileSceneController psc = loader.getController();
		psc.setInstance(dc, currentUser, root, stage, scene, currentUser);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnPost].onMouseClicked
	@FXML
	public void goToPostmaker(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("PostScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		PostSceneController psc = loader.getController();
		psc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnHome].onMouseClicked
	@FXML
	public void goToHome(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("HomeScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		HomeSceneController hsc = loader.getController();
		hsc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnOptions].onMouseClicked
	@FXML
	public void goToOptions(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("OptionsScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		OptionsSceneController osc = loader.getController();
		osc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnLike].onMouseClicked
	@FXML
	public void likePost(MouseEvent event) {
		// TODO Autogenerated
		if (originalPost.isLiked(currentUser)) {
			dc.getPost(originalPost.getKey()).removeLike(currentUser);
			dc.save();
			btnLike.setImage(new Image("unliked.png"));
			lblOPostInfo.setText(dc.getUser(originalPost.getUser()).getUsername() + " " + originalPost.getTime() + ": " + originalPost.getText()  + "\nLikes: " + dc.getPost(originalPost.getKey()).likesSize());
		}
		else {
			dc.getPost(originalPost.getKey()).addLike(currentUser);
			dc.save();
			btnLike.setImage(new Image("liked.png"));
			lblOPostInfo.setText(dc.getUser(originalPost.getUser()).getUsername() + " " + originalPost.getTime() + ": " + originalPost.getText()  + "\nLikes: " + dc.getPost(originalPost.getKey()).likesSize());
		}		
	}
	// Event Listener on ImageView[#btnReply].onMouseClicked
	@FXML
	public void goToReply(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("ReplyScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		ReplySceneController rsc = loader.getController();
		rsc.setInstance(dc, currentUser, root, stage, scene, originalPost);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on ImageView[#btnLogout].onMouseClicked
	@FXML
	public void goToLogin(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("LoginScene.fxml"));
		root = loader.load();
		scene = new Scene(root);
		currentUser = "";
		LoginSceneController lsc = loader.getController();
		lsc.setInstance(dc, currentUser, root, stage, scene);
		stage.setScene(scene);
		stage.show();
	}
}
